name: 'IssueOpenerLabeler'
description: 'A GitHub action that sets issue/PR labels based on who created it'
branding:
  icon: tag
  color: green
inputs:
  dir:
    description: 'The root directory'
    required: true
  repo:
    description: 'The owner of the repo. Assign from github.repository. Example, "someowner/somerepo".'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.dir }}
  - ${{ inputs.repo }}
